### ISSUE TITLE
Finish adding language support

### ISSUE THREAD

**Issue by patrickdevivo** [askgitdev/treequery#7]
- [x] bash
- [x] c
- [x] cpp
- [x] csharp
- [x] css
- [x] elm
- [x] golang
- [x] html
- [x] java
- [x] javascript
- [x] lua
- [x] ocaml
- [x] php
- [x] python
- [x] ruby
- [x] rust
- [x] scala
- [ ] svelte
- [x] toml
- [x] typescript
- [x] yaml

**Comment by vaibhavnshah** [comment]
all language supported added in vaibhav-implementations branch in the languages.go file
